FROM python:3.12.8

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app
COPY .env /app/.env

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
